###############################################################################
# Copyright (C) 2011-2012 Sang Chul Choi
#
# This file is part of RNASeq Analysis.
# 
# RNASeq Analysis is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RNASeq Analysis is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RNASeq Analysis.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################
function global-variable {

  # SPECIES must be set before the call of this bash function. $SPECIESFILE
  # contains a list of Genbank formatted genome file names.
  SPECIESFILE=$ROOTANALYSISDIR/species/$SPECIES

  # The subdirectory output contains directories named after the species file.
  # The output species directory would contain all of the results from the
  # analysis.
  # The output species directory would contain 5 subdirectories. 
  # run-mauve contains genome alignments.
  # run-lcb contains alignment blocks that are generated by the genome
  # alignment.
  # run-clonalframe contains the reference species tree estimated by ClonalFrame.
  # run-clonalorigin contains the result from ClonalOrigin.
  # run-analysis should contain all the results. The final results must be from
  # this directory. A manuscript in the subdirectory doc/README will have
  # special words that will be replaced by values from files in run-analysis.
  # Whenever I change the analysis, values must be changed accordingly.
  OUTPUTDIR=$ROOTANALYSISDIR/output
  BASEDIR=$OUTPUTDIR/$SPECIES
  BASERUNANALYSIS=$BASEDIR/run-analysis
  NUMBERDIR=$BASEDIR/$REPETITION
  DATADIR=$NUMBERDIR/data
  BWADIR=$NUMBERDIR/bwa
  SUBREADDIR=$NUMBERDIR/subread
  TRANSCRIPTDIR=$NUMBERDIR/transcript
  MAQDIR=$NUMBERDIR/maq
  BOWTIEDIR=$NUMBERDIR/bowtie
  RUNANALYSIS=$NUMBERDIR/run-analysis

  # The cluster has almost the same file system. I used to used Samba client to
  # use the file system of the cluster. This stopped working. I did not know the
  # reason, which I did not want to know. Since then, I use scp command.
  # Note that the cluster base directory does not contain run-analysis. The
  # basic analysis is done in the local machine.
  CAC_BASEDIR=$CAC_OUTPUTDIR/$SPECIES
  CAC_NUMBERDIR=$CAC_OUTPUTDIR/$SPECIES/$REPETITION_DIR
  CAC_DATADIR=$CAC_NUMBERDIR/data
  CAC_RUNANALYSIS=$CAC_NUMBERDIR/run-analysis

  X11_BASEDIR=$X11_OUTPUTDIR/$SPECIES
  X11_NUMBERDIR=$X11_OUTPUTDIR/$SPECIES/$REPETITION_DIR
  X11_DATADIR=$X11_NUMBERDIR/data
  X11_RUNANALYSIS=$X11_NUMBERDIR/run-analysis
}

