#!/bin/bash
# RNAz is used to find small RNA candidates. Sequence alignments appear to be a
# critical step for finding small RNAs. Phylogenies of streptococcus species could
# be considered to choose species related with Streptococcus mutans.
# Alternatively, I find sequences similar to intergenic regions, and refine the
# alignments using a multiple sequence alignment tool such as MUSCLE. Steps for
# achieving this goal include: 1. Exract intergenic regions including up- and
# down-stream, 2. BLAST the intergenic regions against non-redundant DB to find
# similar sequences, 3. Refine each alignment using MUSCLE, 4. Apply RNAz to the
# alignments for scoring regions for small RNAs, and 5. Find transcripts with high
# score of small RNAs. The transcripts must be defined in advance.

# TODO:
# 1. Try different BLAST options.
# 2. The reference genome name must be chr1 or change chr1 to the reference
# genome name. This is needed for rnazAnnotate.pl to work.
# 
# Functional enrichment: 1. Find gene ontology categories for each gene of S.
# mutans, 2. Do the enrichment test using R. Melissa should be able to do this.
# 

# Header information.
BASEDIR=test/RNAz
NCBIBACTERIADIR=/Volumes/Elements/Documents/Projects/mauve/bacteria
MAKEBLASTDB=downloads/build/ncbi-blast-2.2.25+/bin/makeblastdb
BLASTN=downloads/build/ncbi-blast-2.2.25+/bin/blastn
BLASTP=downloads/build/ncbi-blast-2.2.25+/bin/blastp
MUSCLE=downloads/build/muscle3.8.31_i86darwin64
RNAPLEX=downloads/build/RNAplex-0.2/Progs/RNAplex
INTERGENICFA=output/smutans12/1/data/intergeniconly.fa
TARGETRNA=output/smutans12/1/data/startcodon.fa
REFGENOMEFASTA=/Volumes/Elements/Documents/Projects/mauve/bacteria/Streptococcus_mutans_UA159_uid57947/NC_004350.fna
GENEONLYFA=output/smutans12/1/data/geneonly.fa
REFPROTEINFASTA=/Volumes/Elements/Documents/Projects/mauve/bacteria/Streptococcus_mutans_UA159_uid57947/NC_004350.faa
REFGENOMEPTT=/Volumes/Elements/Documents/Projects/mauve/bacteria/Streptococcus_mutans_UA159_uid57947/NC_004350.ptt
REFGENOMEGFF=/Volumes/Elements/Documents/Projects/mauve/bacteria/Streptococcus_mutans_UA159_uid57947/NC_004350.gff

###########
# Run jobs.
###########

# Enrichment Test
# Find functional categories that enrich for the predicted small RNAs.
# How? I have values for each proteins
# Useful files.
# cp /Users/goshng/Documents/Projects/mauve-analysis/emails/to/mellisa/051811/mannwhitney.R .
# cp /Users/goshng/Documents/Projects/mauve-analysis/emails/to/mellisa/051811/in.gene .
# scp swiftgen:/usr/projects/strep/SpyMGAS315/* .
#
# Download gene_association.goa_uniprot_noiea at Thu Sep 15 17:14:12 EDT 2011
# Download uniref90.fa.gz at Thu Sep 15 16:28:42 EDT 2011
# Download gene_ontology.1_2.obo at Fri Sep 16 10:31:37 EDT 2011
# 1. Prepare protein sequences of S. mutans in FASTA format (NC_004350.faa)
# 2. Prepare protein sequences of uniref90 database in FASTA format, and create BLASTDB file.
# 3. blastp S. mutans sequences against uniref90 database.
# 4. Create a file like SpyMGAS315_go_bacteria.txt using gene_association.goa_uniprot_noiea
# 5. Create another file like SpyMGAS315_go_category_names.txt
# 6. Create a file file like in.gene 
# 7. Use mannwhitney.R or a modified one to test the enrichment.
#############
#cp $REFPROTEINFASTA $BASEDIR
#wget http://www.geneontology.org/gene-associations/submission/gene_association.goa_uniprot.gz -P $BASEDIR
#gunzip $BASEDIR/gene_association.goa_uniprot.gz 
#gunzip $BASEDIR/uniref90/uniref90.fasta.gz
#$MAKEBLASTDB -in $BASEDIR/uniref90/uniref90.fasta \
#  -dbtype prot -title uniref90 -input_type fasta \
#  -out $BASEDIR/uniref90
#$BLASTP -db $BASEDIR/uniref90 -query $REFPROTEINFASTA \
#  -task blastp \
#  -outfmt 6 \
#  -num_threads 8 \
#  -evalue 0.001 \
#  -out $BASEDIR/geneonly.blast
#wget http://www.geneontology.org/ontology/obo_format_1_2/gene_ontology.1_2.obo -P $BASEDIR
# A machine at the cluster was used.
#perl pl/geneontology.pl gene2go \
#  -gff $REFGENOMEGFF \
#  -blast $BASEDIR/geneonly.blast \
#  -goa $BASEDIR/gene_association.goa_uniprot \
#  -out $BASEDIR/smutans.gene2go

#perl pl/geneontology.pl go2ngene \
#  -gene2go $BASEDIR/smutans.gene2go \
#  -obo $BASEDIR/gene_ontology.1_2.obo \
#  -out $BASEDIR/smutans.go2ngene
Rscript R/mannwhitney.R > $BASEDIR/target_go.txt

exit

#################
# Main procedures
#################

# Create a FASTA file with bacterial genome sequences.
cat `find $NCBIBACTERIADIR -name *.fna | grep -v NC_013928` > $BASEDIR/bacteria.fa

# Create BLAST DB of the FASTA file.
$MAKEBLASTDB -in $BASEDIR/bacteria.fa \
  -dbtype nucl -title bacteria -input_type fasta \
  -out $BASEDIR/bacteria

# BLAST intergenic regions against the BLAST DB.
$BLASTN -db $BASEDIR/bacteria -query $INTERGENICFA \
  -task blastn \
  -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen qseq slen sseq' \
  -num_threads 4 \
  -evalue 0.001 \
  -out $BASEDIR/intergeniconly.blast

# Extract sequence alignments.
rm -rf $BASEDIR/intergeniconly 
mkdir $BASEDIR/intergeniconly 
perl  pl/extract-msa.pl clust -in $BASEDIR/intergeniconly.blast \
  -reference NC_004350 \
  -muscle $MUSCLE \
  -outdir $BASEDIR/intergeniconly

# Align sequences using MUSCLE
rm -rf $BASEDIR/aln
mkdir $BASEDIR/aln
for f in `ls $BASEDIR/intergeniconly`; do
  $MUSCLE -in $BASEDIR/intergeniconly/$f -out $BASEDIR/aln/$f -quiet
done

# Convert FASTA-format alignments to MSA-foramt ones.
perl pl/extract-msa.pl muscle \
  -genomeLength 2030921 \
  -indir $BASEDIR/aln \
  -out $BASEDIR/intergeniconly.maf

# Apply RNAz to the mulitple sequence alignments.
# From Stefan:
# I guess the input to rnazCluster.pl was not sorted correctly.
# Please sort the RNAz results first by chrom and start position and try again.
rnazWindow.pl --max-seq=15 $BASEDIR/intergeniconly.maf > $BASEDIR/intergeniconly.rnaz
# RNAz --show-gaps --both-strands --predict-strand --cutoff=0.5 $BASEDIR/intergeniconly.rnaz > $BASEDIR/rnaz.out
RNAz --show-gaps --cutoff=0.5 $BASEDIR/intergeniconly.rnaz > $BASEDIR/rnaz.out
rm -rf results
rnazCluster.pl --html $BASEDIR/rnaz.out > $BASEDIR/results.dat
rnazAnnotate.pl --bed $BASEDIR/rfam.bed $BASEDIR/results.dat > $BASEDIR/annotated.dat
rnazIndex.pl --bed $BASEDIR/annotated.dat > $BASEDIR/results.bed
rnazIndex.pl --html $BASEDIR/annotated.dat > results/index.html
grep "^locus" $BASEDIR/annotated.dat | cut -f 9 | sort > $BASEDIR/results.known
open results/index.html

# Apply RNAplex
mkdir $BASEDIR/profiles
mv *.ps $BASEDIR/profiles
mv *openen $BASEDIR/profiles
RNAplfold -W 240 -L 160 -u 30 -O < $TARGETRNA > $BASEDIR/target.rnaplfold
RNAplfold -W 40 -L 160 -u 30 -O < $BASEDIR/results.fa

perl pl/feature-genome.pl extract -bed $BASEDIR/results.bed.corrected \
     -in $REFGENOMEFASTA \
     -out $BASEDIR/results.fa
#$RNAPLEX -t $TARGETRNA -q $BASEDIR/results.fa > $BASEDIR/target.rnaplex
$RNAPLEX -t $TARGETRNA -q $BASEDIR/results.fa -l 25 -a $BASEDIR/profiles > $BASEDIR/target.rnaplex.acc
perl pl/rnaplex.pl rank -in $BASEDIR/target.rnaplex.acc -out $BASEDIR/target.rnaplex.acc.out

# Find functional categories that enrich for the predicted small RNAs.

