# Three global variables for a reference genome
SPECIES=cornell
COUNTFILE=output/$SPECIES/1/bwa/count.txt

# for PVALUE in 0.01 0.001 0.0001 0.00001 0.000001; do
for PVALUE in 0.000001; do

CONDDITIONA=835NP
CONDDITIONB=835P
Rscript R/deseq-cornell.R \
  $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
  > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB-$PVALUE.deseq 

done
exit

############################
# UA159, TW1, GLU, and GAL
function run-ua159-tw1-glu-gal {
  SPECIES=cornell
  COUNTFILE=output/$SPECIES/1/bwa/count.txt
  CONDDITIONA=UA159GLU
  CONDDITIONB=UA159GAL
  Rscript R/deseq-cornell.R \
    $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
    > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB.deseq 

  CONDDITIONA=TW1GLU
  CONDDITIONB=TW1GAL
  Rscript R/deseq-cornell.R \
    $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
    > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB.deseq 

  CONDDITIONA=UA159GLU
  CONDDITIONB=TW1GLU
  Rscript R/deseq-cornell.R \
    $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
    > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB.deseq 

  CONDDITIONA=UA159GAL
  CONDDITIONB=TW1GAL
  Rscript R/deseq-cornell.R \
    $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
    > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB.deseq 
}

run-ua159-tw1-glu-gal
exit


# Three global variables for a reference genome
SPECIES=cornell
COUNTFILE=output/$SPECIES/1/bwa/count.txt

for PVALUE in 0.01 0.001 0.0001 0.00001 0.000001; do

CONDDITIONA=835NP
CONDDITIONB=835P
Rscript R/deseq-cornell.R \
  $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
  > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB-$PVALUE.deseq 

CONDDITIONA=UA159GLU
CONDDITIONB=835NP
Rscript R/deseq-cornell.R \
  $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
  > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB-$PVALUE.deseq 

CONDDITIONA=UA159GLU
CONDDITIONB=835P
Rscript R/deseq-cornell.R \
  $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
  > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB-$PVALUE.deseq 

done
exit

############################
# OMZ
SPECIES=omz
COUNTFILE=output/$SPECIES/1/bwa/count.txt
CONDDITIONA=OMZ175
CONDDITIONB=OMZHKRR
Rscript R/deseq-cornell.R \
  $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
  > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB.deseq 

############################
# SMU86
SPECIES=smu86
COUNTFILE=output/$SPECIES/1/bwa/count.txt
CONDDITIONA=Smu86noCSP
CONDDITIONB=Smu86CSP
Rscript R/deseq-cornell.R \
  $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
  > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB.deseq 
exit



CONDDITIONA=OMZ175
CONDDITIONB=OMZHKRR
Rscript R/deseq-cornell.R \
  $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
  > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB.deseq 

PVALUE=0.005
CONDDITIONA=835NP
CONDDITIONB=835P
Rscript R/deseq-cornell.R \
  $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
  > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB.deseq 

CONDDITIONA=UA159GLU
CONDDITIONB=835NP
Rscript R/deseq-cornell.R \
  $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
  > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB-$PVALUE.deseq 

CONDDITIONA=UA159GLU
CONDDITIONB=835P
Rscript R/deseq-cornell.R \
  $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
  > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB-$PVALUE.deseq 

CONDDITIONA=UA159noCSP
CONDDITIONB=UA159CSP
Rscript R/deseq-cornell.R \
  $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
  > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB.deseq 

CONDDITIONA=Smu86noCSP
CONDDITIONB=Smu86CSP
Rscript R/deseq-cornell.R \
  $COUNTFILE $SPECIES $CONDDITIONA $CONDDITIONB $PVALUE \
  > output/$SPECIES/1/bwa/$SPECIES-$CONDDITIONA-$CONDDITIONB.deseq 

